FROM python:3.10-slim

WORKDIR /app

COPY requirements.ui.txt .

RUN pip install --no-cache-dir -r requirements.ui.txt

COPY src ./src

ENV API_URL=http://api:8000
ENV PYTHONUNBUFFERED=1

EXPOSE 8501

CMD ["streamlit", "run", "src/ui.py", "--server.address=0.0.0.0", "--server.port=8501"]
