FROM python:3.10-slim

WORKDIR /app

COPY requirements.api.txt .

RUN pip install --no-cache-dir -r requirements.api.txt

COPY src ./src
COPY model_output ./model_output

ENV MODEL_PATH=model_output
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]
